on:
  push:
    branches:
      - '*'
jobs:
  Test:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
  
  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install

      - name: Deploy
        run: echo "Deploying..."